### ISSUE TITLE
Example sdv.cfb.cfb_teams() call results in error

### ISSUE THREAD

**Issue by KeeonTabrizi** [sportsdataverse/sportsdataverse-py#29]
https://py.sportsdataverse.org/docs/cfb/

### Example:
```
import sportsdataverse as sdv
cfb_df = sportsdataverse.cfb.cfb_teams()

>> 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 sdv.cfb.cfb_teams()

TypeError: 'module' object is not callable

**Comment by armstjc** [comment]
So, one of 2 issues are at hand.

1. cfbFastR-data has it's main branch called 'main', and not 'master' as it's defined in sportsdataverse/config.py
2. The name of the function needs to be renamed to something like 'get_cfb_teams()', instead of 'cfb_teams()'
![image](https://user-images.githubusercontent.com/70788681/176788624-b9af1e5a-b792-44b4-9502-3e8cd44e7475.png)

![image](https://user-images.githubusercontent.com/70788681/176788642-f69105d6-7dfe-4941-9384-1d25632dd7c6.png)

A branch has been created with a potential fix to this bug.
